image: docker

services:
  - docker:dind

before_script:
  - export
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} registry.gitlab.com

build:
  script:
    - docker build -t registry.gitlab.com/zakharii/pigproject .
    - docker push registry.gitlab.com/zakharii/pigproject
